services:
  postgres:
    image: postgres:16
    container_name: vinyler-postgres
    restart: always
    environment:
      POSTGRES_DB: vinyler
      POSTGRES_USER: vinyler-master
      POSTGRES_PASSWORD: itsfrom90s
    ports:
      - 5432:5432

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
#    command: ["redis-service", "--requirepass", "systempass"]
    environment:
      REDIS_ARGS: "--requirepass systempass"
    ports:
      - 6379:6379
      - 8001:8001

  elasticsearch:
    build:
      context: ./docker/elasticsearch
      args:
        ES_VERSION: 8.15.0
    container_name: vinyler-elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: