spring:

  main:
    allow-bean-definition-overriding: true
  application:
    name: Vinyler-server

  datasource:
    url: jdbc:mysql://localhost:3306/vinyler
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vinyler-master
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # jpa가 엔티티 스캔해서 엔티티와 db 테이블을 비교하여 갱신해줌
    show-sql: true
    
springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG  # 인증 관련
    org.springframework.security.web.access: DEBUG         # 인가(Authorization) 관련
    org.springframework.security.jwt: DEBUG                # JWT 관련


jwt:
  secret-key: dmlueWxlci1zY2FuLWl0LXJpZ2h0YXdheS1hdXRob3JpemF0aW9uCg==
  token:
    access-expiration-time: 10800000 # 3시간
    refresh-expiration-time: 604800000 # 7일

data:
  redis:
    host: localhost # 로컬 테스트 시
    port: 6379

