spring:
  application:
    name: Vinyler-server
  datasource:
    url: jdbc:mysql://localhost:3306/vinyler
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vinyler-master
    password: itsfrom90s
  jpa:
    hibernate:
      ddl-auto: update # jpa가 엔티티 스캔해서 엔티티와 db 테이블을 비교하여 갱신해줌
    show-sql: true
springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1