name: "feature_issues_template"
description: "새로운 기능을 제안하는 이슈 템플릿입니다."
title: "[Feature] "
labels: []
assignees: []

body:
  - type: textarea
    id: feature_description
    attributes:
      label: "만들고자 하는 기능"
      description: "추가하려는 기능에 대한 설명을 작성해주세요."
      placeholder: "예: 사용자가 프로필 사진을 변경할 수 있도록 한다."
    validations:
      required: true

  - type: textarea
    id: task_details_text
    attributes:
      label: "작업 상세 내용 (추가 설명)"
      description: "이 기능을 개발하기 위한 추가적인 설명을 작성해주세요."
      placeholder: "예: 1. UI 디자인을 수정해야 함"
    validations:
      required: true

  - type: input
    id: estimated_time
    attributes:
      label: "예상 기간"
      description: "이 작업을 완료하는 데 걸리는 예상 기간을 입력해주세요."
      placeholder: "예: 3월 10일 - 3월 20일"

  - type: textarea
    id: additional_info
    attributes:
      label: "기타 사항"
      description: "추가적으로 고려해야 할 사항이 있다면 작성해주세요."
      placeholder: "예: 이 기능은 백엔드 API와 연동이 필요함."
