
name: Sync issues to jira
on:
  issues:
    types:
      - [labeled]
jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/workflows/issue_form.yml
          

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: BIN
          issuetype: Subtask
          summary: "${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"
          sync-issue-labels: true
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
              }
            }

      - name: Sync to Jira
        uses: atsushii/github-issue-to-jira@v1
        with:
          github-owner: github-owner
          github-repo: repository-name
          github-token: ${{ secrets.GITHUB_TOKEN }} # read/write authorized token
          jira-hostname: hostname # Your Sync dest Jira hostname
          jira-auth-token: ${{ secrets.JIRA_AUTH_TOKEN }} # Your Jira auth token
          jira-auth-email: ${{ secrets.JIRA_AUTH_EMAIL }} # email same as jira project creator
          jira-project-key: project-key # Your Sync dest Jira project name
          synced-label: custom-synced-label
          accepted-label: custom-accepted-label

      - name: Log created issue
        run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"

      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create branch with Ticket number
        run: |
          git checkout -b ${{ steps.create.outputs.issue }}
          git push origin ${{ steps.create.outputs.issue }}

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ steps.create.outputs.issue }} ${{ github.event.issue.title }}"
